### ISSUE TITLE
[Bug]: Can't build on Kubuntu 25.10

### ISSUE THREAD

**Issue by vilbot** [Bali10050/Darkly#286]
### Describe the bug

I get these errors when building:
```
Darkly/kdecoration/darklydecoration.cpp:558:35: error: ‘BorderRadius’ is not a member of ‘KDecoration3’
Darkly/kdecoration/darklydecoration.cpp:558:5: error: ‘setBorderRadius’ was not declared in this scope; did you mean ‘setBorders’?
Darkly/kdecoration/darklydecoration.cpp:561:40: error: ‘BorderOutline’ is not a member of ‘KDecoration3’; did you mean ‘BorderSize’?
Darkly/kdecoration/darklydecoration.cpp:561:9: error: ‘setBorderOutline’ was not declared in this scope
Darkly/kdecoration/darklydecoration.cpp:568:59: error: ‘frameContrast’ is not a member of ‘KColorScheme’
Darkly/kdecoration/darklydecoration.cpp:582:29: error: ‘BorderRadius’ in namespace ‘KDecoration3’ does not name a type
Darkly/kdecoration/darklydecoration.cpp:586:40: error: ‘BorderOutline’ is not a member of ‘KDecoration3’; did you mean ‘BorderSize’?
Darkly/kdecoration/darklydecoration.cpp:586:72: error: ‘outlineRadius’ was not declared in this scope
Darkly/kdecoration/darklydecoration.cpp:586:9: error: ‘setBorderOutline’ was not declared in this scope
Darkly/kdecoration/darklydecoration.cpp:621:35: error: ‘BorderRadius’ is not a member of ‘KDecoration3’
Darkly/kdecoration/darklydecoration.cpp:621:5: error: ‘setBorderRadius’ was not declared in this scope; did you mean ‘setBorders’?
Darkly/kdecoration/darklydecoration.cpp:624:40: error: ‘BorderOutline’ is not a member of ‘KDecoration3’; did you mean ‘BorderSize’?
Darkly/kdecoration/darklydecoration.cpp:624:9: error: ‘setBorderOutline’ was not declared in this scope
Darkly/kdecoration/darklydecoration.cpp:629:59: error: ‘frameContrast’ is not a member of ‘KColorScheme’
Darkly/kdecoration/darklydecoration.cpp:644:43: error: ‘BorderRadius’ is not a member of ‘KDecoration3’
Darkly/kdecoration/darklydecoration.cpp:645:40: error: ‘BorderOutline’ is not a member of ‘KDecoration3’; did you mean ‘BorderSize’?
Darkly/kdecoration/darklydecoration.cpp:645:9: error: ‘setBorderOutline’ was not declared in this scope
```

### Darkly theme version

Darkly 0.5.32

### Plasma version

Plasma 6.4.5

### Qt version

6.9.2

### Add screenshot

.

### Which distribution are you using?

Kubuntu 25.10

### Which color-scheme are you using?

.

### Wayland / X11 session in use?

Wayland

### Is fractional scaling being used?

n
